version: "3"
services:
  vm-builder:
    build: ./
    user: 1000:1000
    privileged: true
    image: dcagatay/qemu-builder:latest
    volumes:
      - "./:/app"
    ports:
      - 5900-6000:5900-6000
